import React, { createContext, useContext, useEffect, useCallback } from 'react';
import type { Vehicle, MaintenanceRecord, ExpenseRecord, DashboardStats, Contact } from '../types';
import { IMMOBILISATIONS_STORAGE_KEY, SAMPLE_IMMOBILISATIONS, type ImmobilisationRecord } from '../types/immobilisations';
import { SINISTRES_STORAGE_KEY, SAMPLE_SINISTRES, type SinistreRecord } from '../types/sinistres';
import { SAMPLE_PNEUS, type PneumatiqueRecord } from '../types/pneumatique';
import { useFirestoreCollection } from '../firestoreSync';

const STORAGE_KEY_VEHICLES = 'parc_auto_vehicles';
const STORAGE_KEY_MAINTENANCE = 'parc_auto_maintenance';
const STORAGE_KEY_EXPENSES = 'parc_auto_expenses';
const STORAGE_KEY_CONTACTS = 'parc_auto_contacts';

// Note : la lecture directe de localStorage n'est plus utilisée pour les collections
// (elles sont désormais synchronisées avec Firestore via useFirestoreCollection).

/**
 * ── Cohérence inter-modules ──
 * Un véhicule doit apparaître comme "En maintenance" (immobilisé) dès qu'il a :
 *  - une immobilisation (Suivi des immobilisations) dont le statut n'est PAS "Terminé", OU
 *  - un sinistre (Gestion des sinistres) actuellement "En réparation"
 *    (les autres statuts de sinistre — Déclaré, Expertise, Indemnisé — n'immobilisent
 *    pas nécessairement le véhicule sur le terrain).
 * On ne rétrograde JAMAIS automatiquement un statut "Hors service" ou "Réformé" : ce sont
 * des décisions manuelles plus lourdes que la synchro ne doit pas écraser. On ne repasse
 * un véhicule en "Actif" que s'il avait été placé en "En maintenance" et qu'il n'a plus
 * aucun dossier actif.
 */
function computeSyncedStatut(
  current: Vehicle['statut'],
  hasActiveImmobilisation: boolean,
  hasActiveSinistre: boolean
): Vehicle['statut'] {
  const shouldBeImmobilized = hasActiveImmobilisation || hasActiveSinistre;
  if (shouldBeImmobilized && current === 'Actif') return 'En maintenance';
  if (!shouldBeImmobilized && current === 'En maintenance') return 'Actif';
  return current;
}

function syncVehiclesWithImmobilisationsAndSinistres(
  vehicleList: Vehicle[],
  immobilisations: ImmobilisationRecord[],
  sinistres: SinistreRecord[]
): Vehicle[] {
  return vehicleList.map((v) => {
    const hasActiveImmobilisation = immobilisations.some((r) => r.vehicleId === v.id && r.statut !== 'Terminé');
    const hasActiveSinistre = sinistres.some((s) => s.vehicleId === v.id && s.statut === 'En réparation');
    const nextStatut = computeSyncedStatut(v.statut, hasActiveImmobilisation, hasActiveSinistre);
    return nextStatut === v.statut ? v : { ...v, statut: nextStatut };
  });
}

const sampleVehicles: Vehicle[] = [
  {
    id: 'v1',
    numero_immatriculation: 'DM-137-MV',
    numero_carte_grise: 'CG45503389',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ352018B8707870',
    marque: 'TOYOTA',
    genre: 'Voiture',
    type_commercial: 'HILUX',
    couleur: 'BLANC',
    carrosserie: 'Pick-up',
    date_mise_circulation: '2023-12-09',
    date_edition: '2023-12-12',
    usage_vehicule: 'Privé',
    energie: 'Diesel',
    places_assises: 2,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2755,
    puissance_fiscale_cv: 14,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VFTEVH0AUMH9DM65R',
    numero_moteur: '',
    type_technique: 'HILUX',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'Actif',
    kilometrage: 4433,
    date_achat: '2023-12-09',
    cout_achat: 4500000,
    date_assurance: '2025-10-14',
    date_vignette: '2025-01-03',
    validite_carte_transport: '2026-02-18',
    validite_patente: '2026-11-20',
    validite_carte_stationnement: '2026-10-07',
    cout_assurance_annuel: 391000,
    affectation: 'Direction Générale',
    zone_affectation: 'Nord',
    categorie_parc: 'Véhicule de fonction',
    conducteur: 'Amadou Kone',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1780000,
    frais_livraison: 234000,
    frais_douane: 360000,
    frais_installation: 100000,
    couts_indirects: 382000,
    consommation_100km: 11.4,
    telephone_gps: '+225 07 15 94 39 47',
  },
  {
    id: 'v2',
    numero_immatriculation: 'GW-174-RN',
    numero_carte_grise: 'CG96282117',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ242019B5443951',
    marque: 'TOYOTA',
    genre: 'Voiture',
    type_commercial: 'LAND CRUISER',
    couleur: 'NOIR',
    carrosserie: 'SUV',
    date_mise_circulation: '2023-02-13',
    date_edition: '2023-02-16',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 5,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 4461,
    puissance_fiscale_cv: 8,
    pv_kg: 0,
    cu_kg: 7,
    vin_chassis: 'VFAWRHEL3E2LSH4DL',
    numero_moteur: '',
    type_technique: 'LAND C',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'Actif',
    kilometrage: 10195,
    date_achat: '2023-02-13',
    cout_achat: 13750000,
    date_assurance: '2025-06-12',
    date_vignette: '2025-11-09',
    validite_carte_transport: '2026-12-19',
    validite_patente: '2026-10-13',
    validite_carte_stationnement: '2026-04-05',
    cout_assurance_annuel: 639000,
    affectation: 'Direction Commerciale',
    zone_affectation: 'Sud',
    categorie_parc: 'Véhicule de service',
    conducteur: 'Fatou Diarra',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 7380000,
    frais_livraison: 245000,
    frais_douane: 1170000,
    frais_installation: 93000,
    couts_indirects: 323000,
    consommation_100km: 11.6,
    telephone_gps: '+225 07 21 16 24 29',
  },
  {
    id: 'v3',
    numero_immatriculation: 'VL-211-RA',
    numero_carte_grise: 'CG25014631',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ392020B6159230',
    marque: 'TOYOTA',
    genre: 'Voiture',
    type_commercial: 'COROLLA',
    couleur: 'MARRON',
    carrosserie: 'Berline',
    date_mise_circulation: '2023-10-03',
    date_edition: '2023-10-06',
    usage_vehicule: 'Professionnel',
    energie: 'Essence',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1798,
    puissance_fiscale_cv: 9,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VFAW0GZBZ6KZC9PA0',
    numero_moteur: '',
    type_technique: 'COROLL',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'Actif',
    kilometrage: 17453,
    date_achat: '2023-10-03',
    cout_achat: 3840000,
    date_assurance: '2026-09-28',
    date_vignette: '2025-11-24',
    validite_carte_transport: '2025-02-24',
    validite_patente: '2026-02-25',
    validite_carte_stationnement: '2025-03-22',
    cout_assurance_annuel: 338000,
    affectation: 'Direction Technique',
    zone_affectation: 'Est',
    categorie_parc: 'Véhicule de pool',
    conducteur: 'Yao Kouassi',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1860000,
    frais_livraison: 217000,
    frais_douane: 530000,
    frais_installation: 137000,
    couts_indirects: 107000,
    consommation_100km: 8.6,
    telephone_gps: '+225 07 80 31 43 77',
  },
  {
    id: 'v4',
    numero_immatriculation: 'RP-248-GD',
    numero_carte_grise: 'CG23009833',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ312021B6944126',
    marque: 'NISSAN',
    genre: 'Voiture',
    type_commercial: 'PATROL',
    couleur: 'ROUGE',
    carrosserie: 'SUV',
    date_mise_circulation: '2018-09-25',
    date_edition: '2018-09-28',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 5,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2999,
    puissance_fiscale_cv: 12,
    pv_kg: 0,
    cu_kg: 7,
    vin_chassis: 'VF43E42M4ZFHYD8XF',
    numero_moteur: '',
    type_technique: 'PATROL',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 72807,
    date_achat: '2018-09-25',
    cout_achat: 9500000,
    date_assurance: '2026-08-17',
    date_vignette: '2026-02-08',
    validite_carte_transport: '2025-11-21',
    validite_patente: '2025-01-13',
    validite_carte_stationnement: '2026-02-08',
    cout_assurance_annuel: 395000,
    affectation: 'Direction Logistique',
    zone_affectation: 'Centre',
    categorie_parc: 'Autre',
    conducteur: 'Aminata Traore',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 3440000,
    frais_livraison: 85000,
    frais_douane: 1200000,
    frais_installation: 108000,
    couts_indirects: 351000,
    consommation_100km: 8.0,
    telephone_gps: '',
  },
  {
    id: 'v5',
    numero_immatriculation: 'KG-285-BU',
    numero_carte_grise: 'CG82772208',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ112023B6261415',
    marque: 'NISSAN',
    genre: 'Voiture',
    type_commercial: 'NAVARA',
    couleur: 'BEIGE',
    carrosserie: 'Pick-up',
    date_mise_circulation: '2017-03-14',
    date_edition: '2017-03-17',
    usage_vehicule: 'Privé',
    energie: 'Diesel',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2488,
    puissance_fiscale_cv: 6,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VFXDS3AR0RGWJUY9C',
    numero_moteur: '',
    type_technique: 'NAVARA',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'Actif',
    kilometrage: 51326,
    date_achat: '2017-03-14',
    cout_achat: 4200000,
    date_assurance: '2025-08-26',
    date_vignette: '2025-01-21',
    validite_carte_transport: '2026-09-28',
    validite_patente: '2025-01-17',
    validite_carte_stationnement: '2025-03-03',
    cout_assurance_annuel: 556000,
    affectation: 'Direction Financière',
    zone_affectation: 'Ouest',
    categorie_parc: 'Véhicule de fonction',
    conducteur: 'Ibrahim Coulibaly',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 2170000,
    frais_livraison: 103000,
    frais_douane: 640000,
    frais_installation: 110000,
    couts_indirects: 135000,
    consommation_100km: 9.3,
    telephone_gps: '+225 07 96 40 61 25',
  },
  {
    id: 'v6',
    numero_immatriculation: 'XT-322-KX',
    numero_carte_grise: 'CG23903144',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ382019B5437001',
    marque: 'HYUNDAI',
    genre: 'Voiture',
    type_commercial: 'TUCSON',
    couleur: 'BLEU',
    carrosserie: 'SUV',
    date_mise_circulation: '2021-10-03',
    date_edition: '2021-10-06',
    usage_vehicule: 'Professionnel',
    energie: 'Essence',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1999,
    puissance_fiscale_cv: 7,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VF64DZG8N4FPJAVK0',
    numero_moteur: '',
    type_technique: 'TUCSON',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 40233,
    date_achat: '2021-10-03',
    cout_achat: 4080000,
    date_assurance: '2026-05-07',
    date_vignette: '2026-04-09',
    validite_carte_transport: '2025-05-10',
    validite_patente: '2025-12-11',
    validite_carte_stationnement: '2025-11-21',
    cout_assurance_annuel: 482000,
    affectation: 'Direction RH',
    zone_affectation: 'Nord',
    categorie_parc: 'Véhicule de service',
    conducteur: 'Awa Bamba',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1530000,
    frais_livraison: 245000,
    frais_douane: 420000,
    frais_installation: 130000,
    couts_indirects: 87000,
    consommation_100km: 6.6,
    telephone_gps: '+225 07 74 72 42 16',
  },
  {
    id: 'v7',
    numero_immatriculation: 'HF-359-FP',
    numero_carte_grise: 'CG13326769',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ152023B6573147',
    marque: 'HYUNDAI',
    genre: 'Utilitaire',
    type_commercial: 'H100',
    couleur: 'ROUGE',
    carrosserie: 'Utilitaire',
    date_mise_circulation: '2024-05-02',
    date_edition: '2024-05-05',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 3,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2607,
    puissance_fiscale_cv: 12,
    pv_kg: 0,
    cu_kg: 3,
    vin_chassis: 'VFP9U82KP2NDF6NT9',
    numero_moteur: '',
    type_technique: 'H100',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 8678,
    date_achat: '2024-05-02',
    cout_achat: 3510000,
    date_assurance: '2026-03-24',
    date_vignette: '2026-09-23',
    validite_carte_transport: '2025-05-06',
    validite_patente: '2025-07-28',
    validite_carte_stationnement: '2025-08-08',
    cout_assurance_annuel: 498000,
    affectation: 'Exploitation Terrain',
    zone_affectation: 'Sud',
    categorie_parc: 'Véhicule de pool',
    conducteur: 'Moussa Diabate',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1620000,
    frais_livraison: 108000,
    frais_douane: 300000,
    frais_installation: 88000,
    couts_indirects: 329000,
    consommation_100km: 6.8,
    telephone_gps: '',
  },
  {
    id: 'v8',
    numero_immatriculation: 'BY-396-PA',
    numero_carte_grise: 'CG79782527',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ392024B4305700',
    marque: 'KIAMOTORS',
    genre: 'Voiture',
    type_commercial: 'SPORTAGE',
    couleur: 'GRIS',
    carrosserie: 'SUV',
    date_mise_circulation: '2018-05-27',
    date_edition: '2018-05-30',
    usage_vehicule: 'Professionnel',
    energie: 'Essence',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1998,
    puissance_fiscale_cv: 11,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VF7GBG26UNLUZ7RCG',
    numero_moteur: '',
    type_technique: 'SPORTA',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 28256,
    date_achat: '2018-05-27',
    cout_achat: 3600000,
    date_assurance: '2026-06-09',
    date_vignette: '2025-05-12',
    validite_carte_transport: '2026-10-11',
    validite_patente: '2025-12-10',
    validite_carte_stationnement: '2026-11-14',
    cout_assurance_annuel: 608000,
    affectation: 'Direction Générale',
    zone_affectation: 'Est',
    categorie_parc: 'Autre',
    conducteur: 'Adjoua Kouame',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1620000,
    frais_livraison: 253000,
    frais_douane: 570000,
    frais_installation: 187000,
    couts_indirects: 219000,
    consommation_100km: 13.1,
    telephone_gps: '',
  },
  {
    id: 'v9',
    numero_immatriculation: 'BH-433-RV',
    numero_carte_grise: 'CG19774839',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ242021B4262081',
    marque: 'KIAMOTORS',
    genre: 'Voiture',
    type_commercial: 'CARENS',
    couleur: 'GRIS',
    carrosserie: 'Familiale',
    date_mise_circulation: '2020-04-14',
    date_edition: '2020-04-17',
    usage_vehicule: 'Privé',
    energie: 'Essence',
    places_assises: 9,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1497,
    puissance_fiscale_cv: 12,
    pv_kg: 0,
    cu_kg: 7,
    vin_chassis: 'VFDZXA5JZM5FKEC91',
    numero_moteur: '',
    type_technique: 'CARENS',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 60187,
    date_achat: '2020-04-14',
    cout_achat: 3600000,
    date_assurance: '2026-07-18',
    date_vignette: '2025-05-10',
    validite_carte_transport: '2025-03-21',
    validite_patente: '2025-02-25',
    validite_carte_stationnement: '2026-04-06',
    cout_assurance_annuel: 387000,
    affectation: 'Direction Commerciale',
    zone_affectation: 'Centre',
    categorie_parc: 'Véhicule de fonction',
    conducteur: 'Seydou Ouattara',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1560000,
    frais_livraison: 228000,
    frais_douane: 460000,
    frais_installation: 132000,
    couts_indirects: 288000,
    consommation_100km: 9.6,
    telephone_gps: '+225 07 99 76 69 16',
  },
  {
    id: 'v10',
    numero_immatriculation: 'YE-470-YG',
    numero_carte_grise: 'CG18620650',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ232021B6551268',
    marque: 'MITSUBISHI',
    genre: 'Voiture',
    type_commercial: 'PAJERO',
    couleur: 'BLEU',
    carrosserie: 'SUV',
    date_mise_circulation: '2016-02-15',
    date_edition: '2016-02-18',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 5,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 3200,
    puissance_fiscale_cv: 14,
    pv_kg: 0,
    cu_kg: 7,
    vin_chassis: 'VFYFHV4JFHML589ER',
    numero_moteur: '',
    type_technique: 'PAJERO',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 84627,
    date_achat: '2016-02-15',
    cout_achat: 8800000,
    date_assurance: '2026-08-20',
    date_vignette: '2026-09-15',
    validite_carte_transport: '2025-04-27',
    validite_patente: '2026-07-25',
    validite_carte_stationnement: '2025-10-13',
    cout_assurance_annuel: 361000,
    affectation: 'Direction Technique',
    zone_affectation: 'Ouest',
    categorie_parc: 'Véhicule de service',
    conducteur: 'Rokia Sangare',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 4380000,
    frais_livraison: 201000,
    frais_douane: 1020000,
    frais_installation: 113000,
    couts_indirects: 376000,
    consommation_100km: 8.4,
    telephone_gps: '+225 07 55 48 59 63',
  },
  {
    id: 'v11',
    numero_immatriculation: 'JP-507-JC',
    numero_carte_grise: 'CG73123515',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ102023B1873851',
    marque: 'MITSUBISHI',
    genre: 'Voiture',
    type_commercial: 'L200',
    couleur: 'MARRON',
    carrosserie: 'Pick-up',
    date_mise_circulation: '2016-08-08',
    date_edition: '2016-08-11',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2442,
    puissance_fiscale_cv: 11,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VF15U8WB3GRLDWLMR',
    numero_moteur: '',
    type_technique: 'L200',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'Actif',
    kilometrage: 72490,
    date_achat: '2016-08-08',
    cout_achat: 4730000,
    date_assurance: '2026-11-22',
    date_vignette: '2026-12-06',
    validite_carte_transport: '2025-11-02',
    validite_patente: '2025-04-07',
    validite_carte_stationnement: '2025-10-05',
    cout_assurance_annuel: 519000,
    affectation: 'Direction Logistique',
    zone_affectation: 'Nord',
    categorie_parc: 'Véhicule de pool',
    conducteur: 'Kader Toure',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 2520000,
    frais_livraison: 239000,
    frais_douane: 580000,
    frais_installation: 150000,
    couts_indirects: 353000,
    consommation_100km: 10.5,
    telephone_gps: '',
  },
  {
    id: 'v12',
    numero_immatriculation: 'RD-544-PM',
    numero_carte_grise: 'CG95306788',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ382024B8713146',
    marque: 'RENAULT',
    genre: 'Voiture',
    type_commercial: 'DUSTER',
    couleur: 'NOIR',
    carrosserie: 'SUV',
    date_mise_circulation: '2017-10-07',
    date_edition: '2017-10-10',
    usage_vehicule: 'Professionnel',
    energie: 'Essence',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1598,
    puissance_fiscale_cv: 8,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VFC4F6K72NUP4ZM0T',
    numero_moteur: '',
    type_technique: 'DUSTER',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 80439,
    date_achat: '2017-10-07',
    cout_achat: 3720000,
    date_assurance: '2025-10-20',
    date_vignette: '2025-03-10',
    validite_carte_transport: '2026-10-26',
    validite_patente: '2026-08-14',
    validite_carte_stationnement: '2026-06-28',
    cout_assurance_annuel: 335000,
    affectation: 'Direction Financière',
    zone_affectation: 'Sud',
    categorie_parc: 'Autre',
    conducteur: 'Mariam Cisse',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1730000,
    frais_livraison: 159000,
    frais_douane: 460000,
    frais_installation: 146000,
    couts_indirects: 253000,
    consommation_100km: 13.1,
    telephone_gps: '',
  },
  {
    id: 'v13',
    numero_immatriculation: 'KX-581-UM',
    numero_carte_grise: 'CG73519947',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ272022B6767292',
    marque: 'PEUGEOT',
    genre: 'Voiture',
    type_commercial: '3008',
    couleur: 'MARRON',
    carrosserie: 'SUV',
    date_mise_circulation: '2024-08-08',
    date_edition: '2024-08-11',
    usage_vehicule: 'Privé',
    energie: 'Essence',
    places_assises: 5,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1598,
    puissance_fiscale_cv: 12,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VFC5FTYFXYV15JESF',
    numero_moteur: '',
    type_technique: '3008',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Actif',
    kilometrage: 12086,
    date_achat: '2024-08-08',
    cout_achat: 3960000,
    date_assurance: '2026-01-16',
    date_vignette: '2026-03-16',
    validite_carte_transport: '2026-06-23',
    validite_patente: '2026-05-10',
    validite_carte_stationnement: '2026-04-04',
    cout_assurance_annuel: 388000,
    affectation: 'Direction RH',
    zone_affectation: 'Est',
    categorie_parc: 'Véhicule de fonction',
    conducteur: 'Bakary Sy',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1660000,
    frais_livraison: 146000,
    frais_douane: 420000,
    frais_installation: 120000,
    couts_indirects: 334000,
    consommation_100km: 6.6,
    telephone_gps: '+225 07 50 25 78 98',
  },
  {
    id: 'v14',
    numero_immatriculation: 'DC-618-NR',
    numero_carte_grise: 'CG19943140',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ282023B1899411',
    marque: 'FORD',
    genre: 'Voiture',
    type_commercial: 'RANGER',
    couleur: 'BEIGE',
    carrosserie: 'Pick-up',
    date_mise_circulation: '2022-04-24',
    date_edition: '2022-04-27',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 5,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 3198,
    puissance_fiscale_cv: 8,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VF3J8Y60JXXVMB3GX',
    numero_moteur: '',
    type_technique: 'RANGER',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'Actif',
    kilometrage: 14819,
    date_achat: '2022-04-24',
    cout_achat: 5520000,
    date_assurance: '2026-02-27',
    date_vignette: '2025-05-08',
    validite_carte_transport: '2026-02-08',
    validite_patente: '2025-09-25',
    validite_carte_stationnement: '2026-10-20',
    cout_assurance_annuel: 464000,
    affectation: 'Exploitation Terrain',
    zone_affectation: 'Centre',
    categorie_parc: 'Véhicule de service',
    conducteur: 'Aya N\'Guessan',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 2130000,
    frais_livraison: 83000,
    frais_douane: 750000,
    frais_installation: 82000,
    couts_indirects: 190000,
    consommation_100km: 6.8,
    telephone_gps: '+225 07 38 76 58 67',
  },
  {
    id: 'v15',
    numero_immatriculation: 'JE-655-CB',
    numero_carte_grise: 'CG32269779',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ352020B5842082',
    marque: 'ISUZU',
    genre: 'Voiture',
    type_commercial: 'D-MAX',
    couleur: 'BLEU',
    carrosserie: 'Pick-up',
    date_mise_circulation: '2018-10-14',
    date_edition: '2018-10-17',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2999,
    puissance_fiscale_cv: 13,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VFXJ2EJJW4EGCU7E9',
    numero_moteur: '',
    type_technique: 'D-MAX',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'En maintenance',
    kilometrage: 84964,
    date_achat: '2018-10-14',
    cout_achat: 4840000,
    date_assurance: '2025-04-21',
    date_vignette: '2025-05-22',
    validite_carte_transport: '2026-12-13',
    validite_patente: '2026-09-18',
    validite_carte_stationnement: '2026-08-03',
    cout_assurance_annuel: 321000,
    affectation: 'Direction Générale',
    zone_affectation: 'Ouest',
    categorie_parc: 'Véhicule de pool',
    conducteur: 'Drissa Sanogo',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1840000,
    frais_livraison: 124000,
    frais_douane: 600000,
    frais_installation: 90000,
    couts_indirects: 51000,
    consommation_100km: 9.4,
    telephone_gps: '+225 07 65 51 87 42',
  },
  {
    id: 'v16',
    numero_immatriculation: 'DN-692-SA',
    numero_carte_grise: 'CG98269682',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ372022B8750676',
    marque: 'MERCEDES-BENZ',
    genre: 'Utilitaire',
    type_commercial: 'SPRINTER',
    couleur: 'NOIR',
    carrosserie: 'Utilitaire',
    date_mise_circulation: '2024-04-22',
    date_edition: '2024-04-25',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 6,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2987,
    puissance_fiscale_cv: 12,
    pv_kg: 0,
    cu_kg: 3,
    vin_chassis: 'VFML6AMTYJS2W5LGL',
    numero_moteur: '',
    type_technique: 'SPRINT',
    numero_immatriculation_precedent: '',
    societe_credit: 'SOGEFINANCE CI',
    statut: 'En maintenance',
    kilometrage: 16030,
    date_achat: '2024-04-22',
    cout_achat: 5310000,
    date_assurance: '2025-03-16',
    date_vignette: '2026-05-06',
    validite_carte_transport: '2026-10-25',
    validite_patente: '2026-11-15',
    validite_carte_stationnement: '2025-04-09',
    cout_assurance_annuel: 579000,
    affectation: 'Direction Commerciale',
    zone_affectation: 'Nord',
    categorie_parc: 'Autre',
    conducteur: '',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 2320000,
    frais_livraison: 288000,
    frais_douane: 630000,
    frais_installation: 73000,
    couts_indirects: 290000,
    consommation_100km: 8.9,
    telephone_gps: '+225 07 46 66 99 72',
  },
  {
    id: 'v17',
    numero_immatriculation: 'PL-729-SJ',
    numero_carte_grise: 'CG10344303',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ192023B6008935',
    marque: 'TOYOTA',
    genre: 'Utilitaire',
    type_commercial: 'HIACE',
    couleur: 'BLEU',
    carrosserie: 'Minibus',
    date_mise_circulation: '2023-11-20',
    date_edition: '2023-11-23',
    usage_vehicule: 'Privé',
    energie: 'Diesel',
    places_assises: 6,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 2982,
    puissance_fiscale_cv: 13,
    pv_kg: 0,
    cu_kg: 14,
    vin_chassis: 'VFJZHTXXFW9RCZ84H',
    numero_moteur: '',
    type_technique: 'HIACE',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'En maintenance',
    kilometrage: 10835,
    date_achat: '2023-11-20',
    cout_achat: 4800000,
    date_assurance: '2025-09-14',
    date_vignette: '2025-04-27',
    validite_carte_transport: '2026-09-16',
    validite_patente: '2026-06-18',
    validite_carte_stationnement: '2026-08-11',
    cout_assurance_annuel: 338000,
    affectation: 'Direction Technique',
    zone_affectation: 'Sud',
    categorie_parc: 'Véhicule de fonction',
    conducteur: '',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 2120000,
    frais_livraison: 110000,
    frais_douane: 630000,
    frais_installation: 89000,
    couts_indirects: 305000,
    consommation_100km: 13.0,
    telephone_gps: '+225 07 99 40 83 59',
  },
  {
    id: 'v18',
    numero_immatriculation: 'TB-766-VC',
    numero_carte_grise: 'CG41510328',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ302023B5821419',
    marque: 'SUZUKI',
    genre: 'Voiture',
    type_commercial: 'JIMNY',
    couleur: 'MARRON',
    carrosserie: 'SUV',
    date_mise_circulation: '2022-01-11',
    date_edition: '2022-01-14',
    usage_vehicule: 'Professionnel',
    energie: 'Essence',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1462,
    puissance_fiscale_cv: 9,
    pv_kg: 0,
    cu_kg: 4,
    vin_chassis: 'VFW09T94XGMS5MRLY',
    numero_moteur: '',
    type_technique: 'JIMNY',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Hors service',
    kilometrage: 50748,
    date_achat: '2022-01-11',
    cout_achat: 2880000,
    date_assurance: '2026-11-26',
    date_vignette: '2025-08-02',
    validite_carte_transport: '2026-02-25',
    validite_patente: '2025-08-06',
    validite_carte_stationnement: '2026-01-02',
    cout_assurance_annuel: 344000,
    affectation: 'Direction Logistique',
    zone_affectation: 'Est',
    categorie_parc: 'Véhicule de service',
    conducteur: '',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1290000,
    frais_livraison: 231000,
    frais_douane: 300000,
    frais_installation: 75000,
    couts_indirects: 275000,
    consommation_100km: 7.2,
    telephone_gps: '',
  },
  {
    id: 'v19',
    numero_immatriculation: 'GN-803-RD',
    numero_carte_grise: 'CG41837210',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ222022B7022335',
    marque: 'VOLKSWAGEN',
    genre: 'Voiture',
    type_commercial: 'AMAROK',
    couleur: 'MARRON',
    carrosserie: 'Pick-up',
    date_mise_circulation: '2025-06-12',
    date_edition: '2025-06-15',
    usage_vehicule: 'Professionnel',
    energie: 'Diesel',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1968,
    puissance_fiscale_cv: 10,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VFGWG0WJA4VNKUGWK',
    numero_moteur: '',
    type_technique: 'AMAROK',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Hors service',
    kilometrage: 3711,
    date_achat: '2025-06-12',
    cout_achat: 5160000,
    date_assurance: '2025-03-06',
    date_vignette: '2025-10-28',
    validite_carte_transport: '2026-01-27',
    validite_patente: '2026-05-01',
    validite_carte_stationnement: '2025-10-24',
    cout_assurance_annuel: 475000,
    affectation: 'Direction Financière',
    zone_affectation: 'Centre',
    categorie_parc: 'Véhicule de pool',
    conducteur: '',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 2440000,
    frais_livraison: 141000,
    frais_douane: 610000,
    frais_installation: 199000,
    couts_indirects: 123000,
    consommation_100km: 8.1,
    telephone_gps: '+225 07 46 39 87 55',
  },
  {
    id: 'v20',
    numero_immatriculation: 'TM-840-CN',
    numero_carte_grise: 'CG11868130',
    nom_proprietaire: 'REHUEL IVOIRIENNE DE SERVICES',
    rdc: 'CIABJ182022B3073474',
    marque: 'NISSAN',
    genre: 'Voiture',
    type_commercial: 'X-TRAIL',
    couleur: 'ROUGE',
    carrosserie: 'SUV',
    date_mise_circulation: '2021-10-09',
    date_edition: '2021-10-12',
    usage_vehicule: 'Professionnel',
    energie: 'Essence',
    places_assises: 4,
    ptac_kg: 0,
    nombre_essieux: 5,
    cylindree_cc: 1997,
    puissance_fiscale_cv: 13,
    pv_kg: 0,
    cu_kg: 5,
    vin_chassis: 'VF8PZHAGXJM7W49ES',
    numero_moteur: '',
    type_technique: 'X-TRAI',
    numero_immatriculation_precedent: '',
    societe_credit: '',
    statut: 'Réformé',
    kilometrage: 27965,
    date_achat: '2021-10-09',
    cout_achat: 3300000,
    date_assurance: '2025-05-26',
    date_vignette: '2026-01-19',
    validite_carte_transport: '2026-10-13',
    validite_patente: '2026-02-22',
    validite_carte_stationnement: '2025-08-01',
    cout_assurance_annuel: 466000,
    affectation: 'Direction RH',
    zone_affectation: 'Ouest',
    categorie_parc: 'Autre',
    conducteur: '',
    observations: 'Véhicule de démonstration',
    valeur_residuelle: 1630000,
    frais_livraison: 103000,
    frais_douane: 500000,
    frais_installation: 133000,
    couts_indirects: 262000,
    consommation_100km: 7.7,
    telephone_gps: '+225 07 81 51 88 38',
  },
];

const sampleExpenses: ExpenseRecord[] = [
  {
    id: 'exp1',
    vehicleId: 'v13',
    date: '2025-08-05',
    categorie: 'Péage',
    libelle: 'Péage autoroute',
    montant: 1000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202508-0001',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp2',
    vehicleId: 'v14',
    date: '2025-08-18',
    categorie: 'Carburant',
    libelle: 'Complément carburant',
    montant: 33000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202508-0002',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp3',
    vehicleId: 'v5',
    date: '2025-08-14',
    categorie: 'Réparation',
    libelle: 'Réparation freins',
    montant: 336000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202508-0003',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp4',
    vehicleId: 'v18',
    date: '2025-08-16',
    categorie: 'Entretien',
    libelle: 'Révision périodique',
    montant: 89000,
    fournisseur: 'Société Ivoirienne de Pneumatiques',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202508-0004',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2025-08-16',
    kilometrage_entretien: 31647,
  },
  {
    id: 'exp5',
    vehicleId: 'v15',
    date: '2025-08-24',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 17000,
    fournisseur: 'Station Shell Zone 4',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202508-0005',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp6',
    vehicleId: 'v12',
    date: '2025-08-23',
    categorie: 'Assurance',
    libelle: 'Prime assurance annuelle',
    montant: 327000,
    fournisseur: 'SIP',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202508-0006',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp7',
    vehicleId: 'v15',
    date: '2025-09-01',
    categorie: 'Entretien',
    libelle: 'Vidange + filtres',
    montant: 44000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202509-0007',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2025-09-01',
    kilometrage_entretien: 58737,
  },
  {
    id: 'exp8',
    vehicleId: 'v18',
    date: '2025-09-13',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 19000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202509-0008',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp9',
    vehicleId: 'v8',
    date: '2025-09-22',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 41000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202509-0009',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp10',
    vehicleId: 'v18',
    date: '2025-09-15',
    categorie: 'Entretien',
    libelle: 'Vidange + filtres',
    montant: 80000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202509-0010',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2025-09-15',
    kilometrage_entretien: 38685,
  },
  {
    id: 'exp11',
    vehicleId: 'v2',
    date: '2025-09-20',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 33000,
    fournisseur: 'SIP',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202509-0011',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp12',
    vehicleId: 'v12',
    date: '2025-09-20',
    categorie: 'Réparation',
    libelle: 'Réparation climatisation',
    montant: 288000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202509-0012',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp13',
    vehicleId: 'v12',
    date: '2025-10-17',
    categorie: 'Carburant',
    libelle: 'Complément carburant',
    montant: 32000,
    fournisseur: 'Station Shell Zone 4',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202510-0013',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp14',
    vehicleId: 'v7',
    date: '2025-10-20',
    categorie: 'Lavage',
    libelle: 'Lavage complet véhicule',
    montant: 8000,
    fournisseur: 'SIP',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202510-0014',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp15',
    vehicleId: 'v20',
    date: '2025-10-23',
    categorie: 'Pièces',
    libelle: 'Achat batterie',
    montant: 106000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202510-0015',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp16',
    vehicleId: 'v12',
    date: '2025-10-21',
    categorie: 'Parking',
    libelle: 'Frais de stationnement',
    montant: 8000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202510-0016',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp17',
    vehicleId: 'v3',
    date: '2025-10-13',
    categorie: 'Péage',
    libelle: 'Péage autoroute',
    montant: 4000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202510-0017',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp18',
    vehicleId: 'v5',
    date: '2025-11-17',
    categorie: 'Entretien',
    libelle: 'Révision périodique',
    montant: 54000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202511-0018',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2025-11-17',
    kilometrage_entretien: 58155,
  },
  {
    id: 'exp19',
    vehicleId: 'v12',
    date: '2025-11-24',
    categorie: 'Amende',
    libelle: 'Amende stationnement',
    montant: 66000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202511-0019',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp20',
    vehicleId: 'v16',
    date: '2025-11-05',
    categorie: 'Vignette',
    libelle: 'Paiement vignette',
    montant: 137000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202511-0020',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp21',
    vehicleId: 'v15',
    date: '2025-11-17',
    categorie: 'Assurance',
    libelle: 'Prime assurance annuelle',
    montant: 446000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202511-0021',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp22',
    vehicleId: 'v15',
    date: '2025-12-07',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 18000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202512-0022',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp23',
    vehicleId: 'v9',
    date: '2025-12-05',
    categorie: 'Amende',
    libelle: 'Amende excès de vitesse',
    montant: 30000,
    fournisseur: 'Station Shell Zone 4',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202512-0023',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp24',
    vehicleId: 'v12',
    date: '2025-12-07',
    categorie: 'Entretien',
    libelle: 'Contrôle technique',
    montant: 76000,
    fournisseur: 'SIP',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202512-0024',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2025-12-07',
    kilometrage_entretien: 53197,
  },
  {
    id: 'exp25',
    vehicleId: 'v8',
    date: '2025-12-04',
    categorie: 'Pièces',
    libelle: 'Achat batterie',
    montant: 193000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202512-0025',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp26',
    vehicleId: 'v11',
    date: '2025-12-23',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 16000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202512-0026',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp27',
    vehicleId: 'v15',
    date: '2025-12-04',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 32000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202512-0027',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp28',
    vehicleId: 'v10',
    date: '2025-12-21',
    categorie: 'Réparation',
    libelle: 'Réparation freins',
    montant: 278000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202512-0028',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp29',
    vehicleId: 'v16',
    date: '2025-12-17',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 29000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202512-0029',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp30',
    vehicleId: 'v5',
    date: '2026-01-02',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 35000,
    fournisseur: 'Société Ivoirienne de Pneumatiques',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202601-0030',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp31',
    vehicleId: 'v9',
    date: '2026-01-06',
    categorie: 'Entretien',
    libelle: 'Vidange + filtres',
    montant: 76000,
    fournisseur: 'Station Shell Zone 4',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202601-0031',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2026-01-06',
    kilometrage_entretien: 32516,
  },
  {
    id: 'exp32',
    vehicleId: 'v16',
    date: '2026-01-03',
    categorie: 'Carburant',
    libelle: 'Complément carburant',
    montant: 35000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202601-0032',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp33',
    vehicleId: 'v10',
    date: '2026-01-01',
    categorie: 'Entretien',
    libelle: 'Contrôle technique',
    montant: 40000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202601-0033',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2026-01-01',
    kilometrage_entretien: 31611,
  },
  {
    id: 'exp34',
    vehicleId: 'v17',
    date: '2026-01-23',
    categorie: 'Vignette',
    libelle: 'Paiement vignette',
    montant: 117000,
    fournisseur: 'Station Shell Zone 4',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202601-0034',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp35',
    vehicleId: 'v15',
    date: '2026-01-13',
    categorie: 'Assurance',
    libelle: 'Prime assurance annuelle',
    montant: 552000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202601-0035',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp36',
    vehicleId: 'v3',
    date: '2026-02-26',
    categorie: 'Lavage',
    libelle: 'Lavage complet véhicule',
    montant: 4000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202602-0036',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp37',
    vehicleId: 'v5',
    date: '2026-02-20',
    categorie: 'Entretien',
    libelle: 'Contrôle technique',
    montant: 118000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202602-0037',
    justificatif_nom: '',
    notes: '',
    date_entretien: '2026-02-20',
    kilometrage_entretien: 35281,
  },
  {
    id: 'exp38',
    vehicleId: 'v16',
    date: '2026-02-22',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 31000,
    fournisseur: 'Société Ivoirienne de Pneumatiques',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202602-0038',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp39',
    vehicleId: 'v15',
    date: '2026-02-17',
    categorie: 'Autre',
    libelle: 'Frais divers',
    montant: 43000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202602-0039',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp40',
    vehicleId: 'v16',
    date: '2026-02-08',
    categorie: 'Amende',
    libelle: 'Amende excès de vitesse',
    montant: 48000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202602-0040',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp41',
    vehicleId: 'v11',
    date: '2026-02-04',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 39000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202602-0041',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp42',
    vehicleId: 'v9',
    date: '2026-03-25',
    categorie: 'Lavage',
    libelle: 'Lavage complet véhicule',
    montant: 7000,
    fournisseur: 'Station Shell Zone 4',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202603-0042',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp43',
    vehicleId: 'v13',
    date: '2026-03-01',
    categorie: 'Pièces',
    libelle: 'Achat plaquettes de frein',
    montant: 177000,
    fournisseur: 'SIP',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202603-0043',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp44',
    vehicleId: 'v18',
    date: '2026-03-02',
    categorie: 'Carburant',
    libelle: 'Complément carburant',
    montant: 30000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202603-0044',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp45',
    vehicleId: 'v6',
    date: '2026-03-06',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 31000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202603-0045',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp46',
    vehicleId: 'v18',
    date: '2026-03-11',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 22000,
    fournisseur: 'SIP',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202603-0046',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp47',
    vehicleId: 'v2',
    date: '2026-03-25',
    categorie: 'Réparation',
    libelle: 'Réparation climatisation',
    montant: 114000,
    fournisseur: 'Société Ivoirienne de Pneumatiques',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202603-0047',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp48',
    vehicleId: 'v1',
    date: '2026-03-10',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 28000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202603-0048',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp49',
    vehicleId: 'v5',
    date: '2026-04-05',
    categorie: 'Réparation',
    libelle: 'Réparation suspension',
    montant: 419000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202604-0049',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp50',
    vehicleId: 'v9',
    date: '2026-04-05',
    categorie: 'Réparation',
    libelle: 'Réparation suspension',
    montant: 441000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202604-0050',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp51',
    vehicleId: 'v10',
    date: '2026-04-18',
    categorie: 'Autre',
    libelle: 'Frais divers',
    montant: 50000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202604-0051',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp52',
    vehicleId: 'v16',
    date: '2026-04-07',
    categorie: 'Amende',
    libelle: 'Amende excès de vitesse',
    montant: 73000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202604-0052',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp53',
    vehicleId: 'v13',
    date: '2026-04-22',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 40000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202604-0053',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp54',
    vehicleId: 'v20',
    date: '2026-05-04',
    categorie: 'Réparation',
    libelle: 'Réparation suspension',
    montant: 298000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202605-0054',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp55',
    vehicleId: 'v2',
    date: '2026-05-02',
    categorie: 'Carburant',
    libelle: 'Complément carburant',
    montant: 29000,
    fournisseur: 'Société Ivoirienne de Pneumatiques',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202605-0055',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp56',
    vehicleId: 'v13',
    date: '2026-05-10',
    categorie: 'Lavage',
    libelle: 'Lavage complet véhicule',
    montant: 4000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202605-0056',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp57',
    vehicleId: 'v10',
    date: '2026-05-25',
    categorie: 'Lavage',
    libelle: 'Lavage complet véhicule',
    montant: 10000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202605-0057',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp58',
    vehicleId: 'v13',
    date: '2026-05-08',
    categorie: 'Carburant',
    libelle: 'Complément carburant',
    montant: 16000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202605-0058',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp59',
    vehicleId: 'v11',
    date: '2026-05-24',
    categorie: 'Pièces',
    libelle: 'Achat batterie',
    montant: 141000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202605-0059',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp60',
    vehicleId: 'v5',
    date: '2026-06-16',
    categorie: 'Pièces',
    libelle: 'Achat plaquettes de frein',
    montant: 137000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202606-0060',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp61',
    vehicleId: 'v6',
    date: '2026-06-13',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 17000,
    fournisseur: 'Auto Service Abidjan',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202606-0061',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp62',
    vehicleId: 'v14',
    date: '2026-06-04',
    categorie: 'Réparation',
    libelle: 'Réparation climatisation',
    montant: 138000,
    fournisseur: 'SIP',
    mode_paiement: 'Chèque',
    numero_piece: 'PC-202606-0062',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp63',
    vehicleId: 'v9',
    date: '2026-06-09',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 22000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202606-0063',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp64',
    vehicleId: 'v15',
    date: '2026-06-21',
    categorie: 'Autre',
    libelle: 'Frais divers',
    montant: 8000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202606-0064',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp65',
    vehicleId: 'v17',
    date: '2026-06-12',
    categorie: 'Lavage',
    libelle: 'Lavage complet véhicule',
    montant: 6000,
    fournisseur: 'Total Energies CI',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202606-0065',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp66',
    vehicleId: 'v2',
    date: '2026-06-09',
    categorie: 'Assurance',
    libelle: 'Prime assurance annuelle',
    montant: 447000,
    fournisseur: 'Société Ivoirienne de Pneumatiques',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202606-0066',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp67',
    vehicleId: 'v13',
    date: '2026-07-04',
    categorie: 'Péage',
    libelle: 'Péage autoroute',
    montant: 2000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202607-0067',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp68',
    vehicleId: 'v19',
    date: '2026-07-10',
    categorie: 'Amende',
    libelle: 'Amende stationnement',
    montant: 36000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202607-0068',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp69',
    vehicleId: 'v13',
    date: '2026-07-03',
    categorie: 'Assurance',
    libelle: 'Prime assurance annuelle',
    montant: 363000,
    fournisseur: 'Garage Central',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202607-0069',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp70',
    vehicleId: 'v10',
    date: '2026-07-12',
    categorie: 'Carburant',
    libelle: 'Plein gasoil',
    montant: 20000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Espèces',
    numero_piece: 'PC-202607-0070',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp71',
    vehicleId: 'v20',
    date: '2026-07-23',
    categorie: 'Péage',
    libelle: 'Péage autoroute',
    montant: 4000,
    fournisseur: 'Garage Expert',
    mode_paiement: 'Virement',
    numero_piece: 'PC-202607-0071',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp72',
    vehicleId: 'v12',
    date: '2026-07-13',
    categorie: 'Carburant',
    libelle: 'Complément carburant',
    montant: 22000,
    fournisseur: 'SIP',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202607-0072',
    justificatif_nom: '',
    notes: '',
  },
  {
    id: 'exp73',
    vehicleId: 'v19',
    date: '2026-07-10',
    categorie: 'Carburant',
    libelle: 'Plein essence',
    montant: 27000,
    fournisseur: 'Garage KIA',
    mode_paiement: 'Mobile Money',
    numero_piece: 'PC-202607-0073',
    justificatif_nom: '',
    notes: '',
  },
];

const sampleContacts: Contact[] = [
  { id: 'c1', type_contact: 'Garage', nom: 'Garage KIA', societe: 'KIA Côte d\'Ivoire', fonction: 'Atelier mécanique', telephone: '+225 27 22 41 12 34', email: 'contact@kia-ci.com', adresse: 'Zone 4, Boulevard de Marseille', ville: 'Abidjan', pays: 'Côte d\'Ivoire', notes: 'Garage agréé pour entretien et carrosserie', date_creation: '2024-01-15' },
  { id: 'c2', type_contact: 'Assureur', nom: 'Diabaté', prenom: 'Salimata', societe: 'NSIA Assurances', fonction: 'Gestionnaire de comptes flotte', telephone: '+225 07 08 99 11 22', email: 's.diabate@nsia.ci', adresse: 'Avenue Chardy, Plateau', ville: 'Abidjan', pays: 'Côte d\'Ivoire', notes: 'Contrat flotte entreprise n°FL-4521', date_creation: '2024-02-03' },
  { id: 'c3', type_contact: 'Fournisseur', nom: 'Société Ivoirienne de Pneumatiques', societe: 'SIP', fonction: 'Service commercial', telephone: '+225 21 35 67 89', email: 'commercial@sip.ci', adresse: 'Zone industrielle de Yopougon', ville: 'Abidjan', pays: 'Côte d\'Ivoire', notes: 'Fournisseur principal pneus Michelin/Continental', date_creation: '2024-03-10' },
  { id: 'c4', type_contact: 'Administration', nom: 'Direction des Transports Terrestres', societe: 'DTT', fonction: 'Service immatriculation', telephone: '+225 27 20 21 22 23', email: '', adresse: 'Abidjan-Plateau', ville: 'Abidjan', pays: 'Côte d\'Ivoire', notes: 'Renouvellement cartes grises et vignettes', date_creation: '2024-01-20' },
  { id: 'c5', type_contact: 'Client', civilite: 'M.', nom: 'Ouattara', prenom: 'Drissa', societe: 'COTRADIS SARL', fonction: 'Directeur logistique', telephone: '+225 07 45 66 77 88', email: 'd.ouattara@cotradis.ci', adresse: 'Marcory Zone 4', ville: 'Abidjan', pays: 'Côte d\'Ivoire', notes: '', date_creation: '2024-05-12' },
];

interface VehicleContextType {
  vehicles: Vehicle[];
  maintenanceRecords: MaintenanceRecord[];
  expenseRecords: ExpenseRecord[];
  contacts: Contact[];
  immobilisations: ImmobilisationRecord[];
  sinistres: SinistreRecord[];
  pneus: PneumatiqueRecord[];
  setPneus: (updater: PneumatiqueRecord[] | ((prev: PneumatiqueRecord[]) => PneumatiqueRecord[])) => void;
  addVehicle: (vehicle: Vehicle) => void;
  updateVehicle: (id: string, vehicle: Partial<Vehicle>) => void;
  deleteVehicle: (id: string) => void;
  deleteMultipleVehicles: (ids: string[]) => void;
  addMaintenanceRecord: (record: MaintenanceRecord) => void;
  deleteMaintenanceRecord: (id: string) => void;
  addExpenseRecord: (record: ExpenseRecord) => void;
  updateExpenseRecord: (id: string, record: Partial<ExpenseRecord>) => void;
  deleteExpenseRecord: (id: string) => void;
  importExpenseRecords: (records: ExpenseRecord[]) => void;
  getDashboardStats: () => DashboardStats;
  importVehicles: (vehicles: Vehicle[]) => void;
  getVehicleById: (id: string) => Vehicle | undefined;
  addContact: (contact: Contact) => void;
  updateContact: (id: string, contact: Partial<Contact>) => void;
  deleteContact: (id: string) => void;
  addImmobilisation: (record: ImmobilisationRecord) => void;
  updateImmobilisation: (id: string, record: Partial<ImmobilisationRecord>) => void;
  deleteImmobilisation: (id: string) => void;
  addSinistre: (record: SinistreRecord) => void;
  updateSinistre: (id: string, record: Partial<SinistreRecord>) => void;
  deleteSinistre: (id: string) => void;
}

const VehicleContext = createContext<VehicleContextType | undefined>(undefined);

export function VehicleProvider({ children }: { children: React.ReactNode }) {
  const [immobilisations, setImmobilisations] = useFirestoreCollection<ImmobilisationRecord>(
    IMMOBILISATIONS_STORAGE_KEY, SAMPLE_IMMOBILISATIONS
  );
  const [sinistres, setSinistres] = useFirestoreCollection<SinistreRecord>(
    SINISTRES_STORAGE_KEY, SAMPLE_SINISTRES
  );
  const [vehicles, setVehicles] = useFirestoreCollection<Vehicle>(
    STORAGE_KEY_VEHICLES, sampleVehicles
  );
  const [maintenanceRecords, setMaintenanceRecords] = useFirestoreCollection<MaintenanceRecord>(
    STORAGE_KEY_MAINTENANCE, []
  );
  const [expenseRecords, setExpenseRecords] = useFirestoreCollection<ExpenseRecord>(
    STORAGE_KEY_EXPENSES, sampleExpenses
  );
  const [contacts, setContacts] = useFirestoreCollection<Contact>(
    STORAGE_KEY_CONTACTS, sampleContacts
  );
  const [pneus, setPneus] = useFirestoreCollection<PneumatiqueRecord>(
    'parc_auto_pneus', SAMPLE_PNEUS
  );

  // ── Cohérence en temps réel ──
  // Dès qu'une immobilisation ou un sinistre change (ajout, modification,
  // suppression — depuis n'importe quel écran), on recalcule automatiquement
  // le statut des véhicules concernés. Plus besoin d'appel manuel : le menu
  // Véhicules et le Tableau de bord se mettent à jour tout seuls.
  useEffect(() => {
    setVehicles((prev) => syncVehiclesWithImmobilisationsAndSinistres(prev, immobilisations, sinistres));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [immobilisations, sinistres]);

  const addVehicle = useCallback((vehicle: Vehicle) => {
    setVehicles((prev) => [...prev, vehicle]);
  }, []);

  const updateVehicle = useCallback((id: string, updates: Partial<Vehicle>) => {
    setVehicles((prev) => prev.map((v) => (v.id === id ? { ...v, ...updates } : v)));
  }, []);

  const deleteVehicle = useCallback((id: string) => {
    setVehicles((prev) => prev.filter((v) => v.id !== id));
    setMaintenanceRecords((prev) => prev.filter((m) => m.vehicleId !== id));
    setExpenseRecords((prev) => prev.filter((expense) => expense.vehicleId !== id));
  }, []);

  const deleteMultipleVehicles = useCallback((ids: string[]) => {
    const idSet = new Set(ids);
    setVehicles((prev) => prev.filter((v) => !idSet.has(v.id)));
    setMaintenanceRecords((prev) => prev.filter((m) => !idSet.has(m.vehicleId)));
    setExpenseRecords((prev) => prev.filter((expense) => !idSet.has(expense.vehicleId)));
  }, []);

  const addMaintenanceRecord = useCallback((record: MaintenanceRecord) => {
    setMaintenanceRecords((prev) => [...prev, record]);
  }, []);

  const deleteMaintenanceRecord = useCallback((id: string) => {
    setMaintenanceRecords((prev) => prev.filter((m) => m.id !== id));
  }, []);

  const addExpenseRecord = useCallback((record: ExpenseRecord) => {
    setExpenseRecords((prev) => [...prev, record]);
  }, []);

  const updateExpenseRecord = useCallback((id: string, updates: Partial<ExpenseRecord>) => {
    setExpenseRecords((prev) => prev.map((expense) => (expense.id === id ? { ...expense, ...updates } : expense)));
  }, []);

  const deleteExpenseRecord = useCallback((id: string) => {
    setExpenseRecords((prev) => prev.filter((expense) => expense.id !== id));
  }, []);

  const importExpenseRecords = useCallback((records: ExpenseRecord[]) => {
    setExpenseRecords((prev) => [...prev, ...records]);
  }, []);

  const importVehicles = useCallback((newVehicles: Vehicle[]) => {
    setVehicles((prev) => {
      const existingIds = new Set(prev.map((v) => v.numero_immatriculation));
      const toAdd = newVehicles.filter((v) => !existingIds.has(v.numero_immatriculation));
      return [...prev, ...toAdd];
    });
  }, []);

  const getVehicleById = useCallback(
    (id: string) => vehicles.find((v) => v.id === id),
    [vehicles]
  );

  const addContact = useCallback((contact: Contact) => {
    setContacts((prev) => [...prev, contact]);
  }, []);

  const updateContact = useCallback((id: string, updates: Partial<Contact>) => {
    setContacts((prev) => prev.map((c) => (c.id === id ? { ...c, ...updates } : c)));
  }, []);

  const deleteContact = useCallback((id: string) => {
    if (!confirm('Supprimer ce contact du carnet d\'adresses ?')) return;
    setContacts((prev) => prev.filter((c) => c.id !== id));
  }, []);

  const addImmobilisation = useCallback((record: ImmobilisationRecord) => {
    setImmobilisations((prev) => [...prev, record]);
  }, []);

  const updateImmobilisation = useCallback((id: string, updates: Partial<ImmobilisationRecord>) => {
    setImmobilisations((prev) => prev.map((r) => (r.id === id ? { ...r, ...updates } : r)));
  }, []);

  const deleteImmobilisation = useCallback((id: string) => {
    setImmobilisations((prev) => prev.filter((r) => r.id !== id));
  }, []);

  const addSinistre = useCallback((record: SinistreRecord) => {
    setSinistres((prev) => [...prev, record]);
  }, []);

  const updateSinistre = useCallback((id: string, updates: Partial<SinistreRecord>) => {
    setSinistres((prev) => prev.map((s) => (s.id === id ? { ...s, ...updates } : s)));
  }, []);

  const deleteSinistre = useCallback((id: string) => {
    setSinistres((prev) => prev.filter((s) => s.id !== id));
  }, []);

  const getDashboardStats = useCallback((): DashboardStats => {
    const now = new Date();
    const thirtyDaysFromNow = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    const activeVehicles = vehicles.filter((v) => v.statut === 'Actif');
    const maintenanceVehicles = vehicles.filter((v) => v.statut === 'En maintenance');
    const outOfServiceVehicles = vehicles.filter((v) => v.statut === 'Hors service');
    const reformedVehicles = vehicles.filter((v) => v.statut === 'Réformé');

    const totalKilometers = vehicles.reduce((sum, v) => sum + v.kilometrage, 0);
    const avgKilometers = vehicles.length > 0 ? totalKilometers / vehicles.length : 0;
    const totalAcquisitionCost = vehicles.reduce((sum, v) => sum + v.cout_achat + (v.frais_livraison || 0) + (v.frais_douane || 0) + (v.frais_installation || 0), 0);
    const totalInsuranceCost = vehicles.reduce((sum, v) => sum + v.cout_assurance_annuel, 0);
    const totalMaintenanceCost = maintenanceRecords.reduce((sum, record) => sum + record.cout, 0);
    const totalExpenseCost = expenseRecords.reduce((sum, expense) => sum + expense.montant, 0);
    const totalIndirectCosts = vehicles.reduce((sum, v) => sum + (v.couts_indirects || 0), 0);
    const totalResidualValue = vehicles.reduce((sum, v) => sum + (v.valeur_residuelle || 0), 0);
    const totalOperatingCost = totalInsuranceCost + totalMaintenanceCost + totalExpenseCost;
    const avgExpensePerVehicle = vehicles.length > 0 ? totalExpenseCost / vehicles.length : 0;
    
    // TCO = Coûts d'acquisition + Coûts d'exploitation + Coûts indirects - Valeur résiduelle
    const tcoGlobal = totalAcquisitionCost + totalOperatingCost + totalIndirectCosts - totalResidualValue;
    const tcoPerVehicle = vehicles.length > 0 ? tcoGlobal / vehicles.length : 0;

    const upcomingInsurance = vehicles.filter((v) => {
      if (!v.date_assurance) return false;
      const d = new Date(v.date_assurance);
      return d <= thirtyDaysFromNow;
    }).length;

    const upcomingVignette = vehicles.filter((v) => {
      if (!v.date_vignette) return false;
      const d = new Date(v.date_vignette);
      return d <= thirtyDaysFromNow;
    }).length;

    const upcomingCarteTransport = vehicles.filter((v) => {
      if (!v.validite_carte_transport) return false;
      const d = new Date(v.validite_carte_transport);
      return d <= thirtyDaysFromNow;
    }).length;

    const upcomingPatente = vehicles.filter((v) => {
      if (!v.validite_patente) return false;
      const d = new Date(v.validite_patente);
      return d <= thirtyDaysFromNow;
    }).length;

    const upcomingCarteStationnement = vehicles.filter((v) => {
      if (!v.validite_carte_stationnement) return false;
      const d = new Date(v.validite_carte_stationnement);
      return d <= thirtyDaysFromNow;
    }).length;

    const energyMap = new Map<string, number>();
    vehicles.forEach((v) => {
      energyMap.set(v.energie, (energyMap.get(v.energie) || 0) + 1);
    });
    const energyDistribution = Array.from(energyMap.entries()).map(([name, value]) => ({ name, value }));

    const brandMap = new Map<string, number>();
    vehicles.forEach((v) => {
      brandMap.set(v.marque, (brandMap.get(v.marque) || 0) + 1);
    });
    const brandDistribution = Array.from(brandMap.entries())
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value);

    const monthMap = new Map<string, number>();
    maintenanceRecords.forEach((m) => {
      const d = new Date(m.date);
      const key = d.toLocaleString('fr-FR', { month: 'short', year: 'numeric' });
      monthMap.set(key, (monthMap.get(key) || 0) + m.cout);
    });
    expenseRecords.forEach((expense) => {
      const d = new Date(expense.date);
      const key = d.toLocaleString('fr-FR', { month: 'short', year: 'numeric' });
      monthMap.set(key, (monthMap.get(key) || 0) + expense.montant);
    });
    const monthlyCosts = Array.from(monthMap.entries())
      .map(([month, cost]) => ({ month, cost }))
      .sort((a, b) => new Date(a.month).getTime() - new Date(b.month).getTime())
      .slice(-6);

    const expenseMonthMap = new Map<string, number>();
    expenseRecords.forEach((expense) => {
      const d = new Date(expense.date);
      const key = d.toLocaleString('fr-FR', { month: 'short', year: 'numeric' });
      expenseMonthMap.set(key, (expenseMonthMap.get(key) || 0) + expense.montant);
    });
    const monthlyExpenses = Array.from(expenseMonthMap.entries())
      .map(([month, cost]) => ({ month, cost }))
      .sort((a, b) => new Date(a.month).getTime() - new Date(b.month).getTime())
      .slice(-6);

    const expenseCategoryMap = new Map<string, number>();
    expenseRecords.forEach((expense) => {
      expenseCategoryMap.set(expense.categorie, (expenseCategoryMap.get(expense.categorie) || 0) + expense.montant);
    });
    const expenseCategoryDistribution = Array.from(expenseCategoryMap.entries())
      .map(([name, value]) => ({ name, value }))
      .sort((a, b) => b.value - a.value);

    const ageMap = new Map<string, number>();
    vehicles.forEach((v) => {
      if (!v.date_mise_circulation) return;
      const age = new Date().getFullYear() - new Date(v.date_mise_circulation).getFullYear();
      const bucket = age <= 1 ? '0-1 ans' : age <= 3 ? '1-3 ans' : age <= 5 ? '3-5 ans' : '5+ ans';
      ageMap.set(bucket, (ageMap.get(bucket) || 0) + 1);
    });
    const vehicleAgeDistribution = Array.from(ageMap.entries()).map(([name, value]) => ({ name, value }));

    const categoryMap = new Map<string, number>();
    vehicles.forEach((v) => {
      const cat = v.categorie_parc || 'Autre';
      categoryMap.set(cat, (categoryMap.get(cat) || 0) + 1);
    });
    const fleetCategoryDistribution = Array.from(categoryMap.entries()).map(([name, value]) => ({ name, value }));

    return {
      totalVehicles: vehicles.length,
      activeVehicles: activeVehicles.length,
      maintenanceVehicles: maintenanceVehicles.length,
      outOfServiceVehicles: outOfServiceVehicles.length,
      reformedVehicles: reformedVehicles.length,
      totalKilometers,
      avgKilometers: Math.round(avgKilometers),
      totalAcquisitionCost,
      totalInsuranceCost,
      totalExpenseCost,
      totalOperatingCost,
      avgExpensePerVehicle: Math.round(avgExpensePerVehicle),
      tcoGlobal: Math.round(tcoGlobal),
      tcoPerVehicle: Math.round(tcoPerVehicle),
      upcomingInsurance,
      upcomingVignette,
      upcomingCarteTransport,
      upcomingPatente,
      upcomingCarteStationnement,
      energyDistribution,
      brandDistribution,
      monthlyCosts,
      monthlyExpenses,
      expenseCategoryDistribution,
      vehicleAgeDistribution,
      fleetCategoryDistribution,
    };
  }, [vehicles, maintenanceRecords, expenseRecords]);

  return React.createElement(VehicleContext.Provider, {
    value: {
      vehicles,
      maintenanceRecords,
      expenseRecords,
      contacts,
      immobilisations,
      sinistres,
      pneus,
      setPneus,
      addVehicle,
      updateVehicle,
      deleteVehicle,
      deleteMultipleVehicles,
      addMaintenanceRecord,
      deleteMaintenanceRecord,
      addExpenseRecord,
      updateExpenseRecord,
      deleteExpenseRecord,
      importExpenseRecords,
      getDashboardStats,
      importVehicles,
      getVehicleById,
      addContact,
      updateContact,
      deleteContact,
      addImmobilisation,
      updateImmobilisation,
      deleteImmobilisation,
      addSinistre,
      updateSinistre,
      deleteSinistre,
    },
  }, children);
}

export function useVehicles() {
  const context = useContext(VehicleContext);
  if (!context) throw new Error('useVehicles must be used within VehicleProvider');
  return context;
}
